# Additional services example
version: '3.4'

services:

  elasticsearch:
    image: "${ELASTICSEARCH_IMAGE_NAME}"
    restart: unless-stopped
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"

  wdqs-frontend:
    image: "${WDQS_FRONTEND_IMAGE_NAME}"
    restart: unless-stopped
    volumes:
      - ./query/default.conf:/templates/default.conf
      - ./query/custom-config.json:/templates/custom-config.json
    depends_on:
      - wdqs-proxy
    networks:
      default:
        aliases:
         - ${WDQS_FRONTEND_HOST}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: /query/
      VIRTUAL_DEST: /
      WIKIBASE_HOST: ${WIKIBASE_HOST}
      WDQS_HOST: wdqs-proxy.svc

  wdqs:
    image: "${WDQS_IMAGE_NAME}"
    restart: unless-stopped
    command: /runBlazegraph.sh
    volumes:
      - query-service-data:/wdqs/data
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      WIKIBASE_HOST: ${WIKIBASE_HOST}
      WDQS_HOST: wdqs.svc
      WDQS_PORT: 9999
      HEAP_SIZE: 4g
    expose:
      - 9999

  wdqs-proxy:
    image: "${WDQS_PROXY_IMAGE_NAME}"
    restart: unless-stopped
    environment:
      PROXY_PASS_HOST: wdqs.svc:9999
    depends_on:
      - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc

  wdqs-updater:
    image: "${WDQS_IMAGE_NAME}"
    restart: unless-stopped
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     WIKIBASE_HOST: ${WIKIBASE_HOST}
     WDQS_HOST: wdqs.svc
     WDQS_PORT: 9999
     WIKIBASE_MAX_DAYS_BACK: ${WIKIBASE_MAX_DAYS_BACK}
     # CONFIG - WIKIBASE_SCHEME can be set to 'https' if the updater should expect https concept uris

  quickstatements:
    image: "${QUICKSTATEMENTS_IMAGE_NAME}"
    restart: unless-stopped
    volumes:
      - quickstatements-data:/quickstatements/data
    depends_on:
      - wikibase
    networks:
      default:
        aliases:
         - ${QUICKSTATEMENTS_HOST}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: /qs/
      VIRTUAL_DEST: /
      QUICKSTATEMENTS_HOST: ${QUICKSTATEMENTS_HOST}
      QS_PUBLIC_SCHEME_HOST_AND_PORT: ${QS_PUBLIC_SCHEME_HOST_AND_PORT}
      WIKIBASE_SCHEME_AND_HOST: https://${VIRTUAL_HOST}
      WB_PUBLIC_SCHEME_HOST_AND_PORT: https://${VIRTUAL_HOST}
      WB_PROPERTY_NAMESPACE: 122
      WB_PROPERTY_PREFIX: "Property:"
      WB_ITEM_NAMESPACE: 120
      WB_ITEM_PREFIX: "Item:"
      # set when you want to provide existing oauth credentials
      # OAUTH_CONSUMER_KEY: ${OAUTH_CONSUMER_KEY}
      # OAUTH_CONSUMER_SECRET: ${OAUTH_CONSUMER_SECRET}

volumes:
  query-service-data:
  elasticsearch-data:
  quickstatements-data:
