version: "3.8"

services:
  openrefine:
    image: vimagick/openrefine:3.7.4
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 3333
      VIRTUAL_PATH: /openrefine/
      VIRTUAL_DEST: /
    volumes:
      - openrefine-data:/data
    restart: unless-stopped

  openrefine-data:
    image: nginx
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: /openrefine-data/
      VIRTUAL_DEST: /
    volumes:
      - ./openrefine/nginx/templates:/etc/nginx/templates
      - openrefine-data:/usr/share/nginx/html/openrefine:ro
    restart: unless-stopped

volumes:
  openrefine-data:
